# Generated by Django 5.2.3 on 2025-07-04 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre o Razón Social del Cliente', max_length=200)),
                ('cif_nif', models.CharField(max_length=20, unique=True, verbose_name='CIF/NIF')),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre o Razón Social del Proveedor', max_length=200)),
                ('cif_nif', models.CharField(max_length=20, unique=True, verbose_name='CIF/NIF')),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(help_text='Número único de la factura', max_length=50, unique=True)),
                ('fecha_emision', models.DateField(help_text='Fecha en que la factura fue emitida')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha límite para el pago de la factura', null=True)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Base Imponible')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=21.0, max_digits=4, verbose_name='% IVA')),
                ('porcentaje_irpf', models.DecimalField(decimal_places=2, default=15.0, max_digits=4, verbose_name='% IRPF')),
                ('importe_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe IVA')),
                ('importe_irpf', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe IRPF')),
                ('total_factura', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Factura')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=10, verbose_name='Estado de la Factura')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_recibidas_de_proveedores', to='core.cliente')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_emitidas_a_clientes', to='core.proveedor')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision', 'numero_factura'],
            },
        ),
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción del concepto de la línea', max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad de unidades', max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad', max_digits=10)),
                ('importe_linea', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe Línea')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='core.factura')),
            ],
            options={
                'verbose_name': 'Línea de Factura',
                'verbose_name_plural': 'Líneas de Factura',
            },
        ),
    ]
